sudo: required
language: generic
service:
  - docker

before_install:
  - docker build -t vlisovets/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true vlisovets/react-test npm test

after_success:
  - docker build -t vlisovets/multi-client ./client
  - docker build -t vlisovets/multi-nginx ./nginx
  - docker build -t vlisovets/multi-server ./server
  - docker build -t vlisovets/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push vlisovets/multi-client
  - docker push vlisovets/multi-nginx
  - docker push vlisovets/multi-server
  - docker push vlisovets/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-central-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-central-1-356055385176
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
